### ISSUE TITLE
Crash on parsing ranked beatmap

### ISSUE THREAD

**Issue by LeaPhant** [Francesco149/ojsama#17]
Trying to parse [this](https://osu.ppy.sh/beatmapsets/654452#osu/1391940) beatmap causes a crash due to the .osu file being malformatted. Since this apparently can happen on ranked beatmaps the parser should ignore malformed metadata.

```Bash
TypeError: Cannot read property 'trim' of undefined
     at parser._setpos (/opt/osu-beatmap-database/node_modules/ojsama/ojsama.js:585:22)
     at parser._property (/opt/osu-beatmap-database/node_modules/ojsama/ojsama.js:597:15)
     at parser._metadata (/opt/osu-beatmap-database/node_modules/ojsama/ojsama.js:604:16)
     at parser.feed_line (/opt/osu-beatmap-database/node_modules/ojsama/ojsama.js:547:25)
     at parser.feed (/opt/osu-beatmap-database/node_modules/ojsama/ojsama.js:566:10)
```

Part in the .osu file that causes the crash:
```
...
Version:Hard
Source:
Tags:FujunIseiKouyuuP  hujuniseikouyuup 不純異性交遊p Vocaloid Megpoid Gumi rizen Iwami Takashi 岩見陸 where's that girl from 
where's that girl from
BeatmapID:1391940
...
```

**Comment by Francesco149** [comment]
fixed in 1.2.5
