### ISSUE TITLE
TypeError: either n300 or nobjects must be specified on some maps

### ISSUE THREAD

**Issue by oamaok** [Francesco149/ojsama#6]
Yo, getting some error reports to my ezpp! analytics with this data:

```json
{
    "version": "1.5.5",
    "url": "https://osu.ppy.sh/beatmapsets/150945/#osu/372245",
    "calculationSettings": {
        "modifiers": 2,
        "accuracy": 0,
        "combo": 6368,
        "misses": 6368
    },
    "pageInfo": {
        "isOldSite": false,
        "isBeatmap": false,
        "beatmapSetId": "150945",
        "beatmapId": "372245",
        "isUnranked": null
    },
    "error": {
        "message": "either n300 or nobjects must be specified",
        "name": "TypeError",
        "stack": "TypeError: either n300 or nobjects must be specified
 at std_accuracy.value (chrome-extension://aimihpobjpagjiakhcpijibnaafdniol/popup.js:1942:23)
 at std_ppv2.calc (chrome-extension://aimihpobjpagjiakhcpijibnaafdniol/popup.js:2090:47)
 at Object.ppv2 (chrome-extension://aimihpobjpagjiakhcpijibnaafdniol/popup.js:2218:39)
 at calculate (chrome-extension://aimihpobjpagjiakhcpijibnaafdniol/popup.js:335:31)"
    },
    "navigator": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
    }
}
```

the stack trace points to https://github.com/Francesco149/ojsama/blob/master/ojsama.js#L1554

could take a look but going to Japan vacation for three weeks

**Comment by oamaok** [comment]
some other cases with the same error:
```json
    "url": "https://osu.ppy.sh/beatmapsets/325158#osu/741477",
    "calculationSettings": {
        "modifiers": 258,
        "accuracy": 0,
        "combo": 197,
        "misses": 197
    },
```
```json
    "url": "https://osu.ppy.sh/beatmapsets/325158#osu/741477",
    "calculationSettings": {
        "modifiers": 258,
        "accuracy": 0,
        "combo": 197,
        "misses": 50
    },
```

**Comment by Francesco149** [comment]
hmm I'm guessing there's an edge case somewhere with 0% accuracy, maybe the n300 calculation goes negative somehow

ill take a look when I can, I should have some time in the next 2 days

**Comment by Francesco149** [comment]
it seems that we need to guard against invalid miss counts.

the maximum amount of misses is the number of objects in the map, not the max combo

for example, for https://osu.ppy.sh/beatmapsets/325158#osu/741477 has 12 objects (3 circles, 8 sliders, 1 spinners) but 197 max combo, and using 12 as nmisses would work correctly, while anything above would cause the n300 calculation to go negative

```
$ curl http://osu.ppy.sh/osu/741477 | node example.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2655    0  2655    0     0   4462      0 --:--:-- --:--:-- --:--:--  5125
AKINO from bless4 & CHiCO with HoneyWorks - MIIRO vs. Ai no Scenario [(AKINO from bless4 & CHiCO with HoneyWorks - 海色 vs. アイのシナリオ)Ultra Beginner] mapped by monstrata

AR0 OD0 CS2 HP0
3 circles, 8 sliders, 1 spinners
197 max combo

0.38 stars (0.20 aim, 0.17 speed)
100.00% 0x100 0x50 0xmiss
197/197x
0.57 pp (0.01 aim, 0.01 speed, 0.50 acc)
```

for now i will add a crappy check that just clamps it between 0 and the number of objects, eventually i'll think of a nicer way to do it
